{% set name = "PyGithub" %}
{% set version = "1.43.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ce91d4990efbfb7a0a1abd06e2106a3998a4a5810a4bdd3c1b6be5499918e9b

build:
  # Cannot use `noarch: python` as this uses 2to3.
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pyjwt
    - requests >=2.14.0
    - deprecated

test:
  requires:
    - pip
  imports:
    - github
  commands:
    - pip check

about:
  home: http://pygithub.github.io/PyGithub
  license_file: COPYING.LESSER
  license: LGPL-3.0-only
  license_family: LGPL
  summary: 'Python library implementing the GitHub API v3'
  doc_url: http://pygithub.github.io/PyGithub
  dev_url: https://github.com/PyGithub/PyGithub

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - xmnlab
