package:
  name: pygithub
  version: "1.26.0"

source:
  fn: PyGithub-1.26.0.tar.gz
  url: https://github.com/PyGithub/PyGithub/archive/v1.26.0.tar.gz
  md5: dfaa786c2420d5734d450ec2ecb8c132

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - github
    - github.tests

about:
  home: http://pygithub.github.io/PyGithub/v1/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: Python library implementing the GitHub API v3

extra:
  recipe-maintainers:
    - pelson
