{% set name = "PyGithub" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 6601e22627e87bac192f1e2e39c6e6f69a43152cfb8f307cee575879320b3051

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools-scm
  run:
    - python
    # pyjwt[crypto] is pyjwt + cryptography
    - pyjwt >=2.4.0
    - cryptography
    - pynacl >=1.4.0
    - requests >=2.14.0
    - typing-extensions >=4.0.0
    - urllib3 >=1.26.0
    - deprecated

test:
  imports:
    - github
  requires:
    - pip
    - httpretty >=1.0.3
    - pytest >=5.3
  source_files:
    - pyproject.toml
    - tests
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/PyGithub/PyGithub
  license_file: COPYING.LESSER
  license: LGPL-3.0-only
  license_family: LGPL
  summary: Python library implementing the GitHub API v3
  description: |
    PyGitHub is a Python library to access the GitHub REST API. This library enables you to manage GitHub resources
    such as repositories, user profiles, and organizations in your Python applications.
  doc_url: https://pygithub.readthedocs.io
  dev_url: https://github.com/PyGithub/PyGithub

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - xmnlab
