{% set name = "PyGithub" %}
{% set version = "1.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ed08f775ec5067bc8452b72bde2dbb95cf4e52ff2bd50cc32c69c91ffad9272

build:
  number: 0
  # Need to use setuptools <58.0 to avoid build error
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python 3.10
    # use_2to3 is a deprecated
    - setuptools <58.0
    - wheel
  run:
    - python >=3.10
    - pyjwt

test:
  imports:
    - github
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyGithub/PyGithub
  license_file: COPYING.LESSER
  license: LGPL-3.0-only
  license_family: LGPL
  summary: Python library implementing the GitHub API v3
  description: |
    PyGitHub is a Python library to access the GitHub REST API. This library enables you to manage GitHub resources
    such as repositories, user profiles, and organizations in your Python applications.
  doc_url: https://pygithub.readthedocs.io
  dev_url: https://github.com/PyGithub/PyGithub

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - xmnlab
