# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Umu8C89Z07BKbEIqUTd8+hIA8fDOWBYAH937UHEtbX97Y4m6616Srb5Zqi4hxCBEPB2IB1pL12JKG4lgNR/Ciz5rjSOZ1bDkGS1RxwtIjl8nhCbxhF+nzYIZRBipSvPQd6FkT4IQoN8StxrJAl22kIt/ibfG6ACOkrqWv6ihjORmUxkx/6pGvE0DUYzTV6GA6A8RwO+Wu3wJ5ejO2uO24pe8+HRE8QtQZm4svOH9aWVKaqAN5oKBB79MemvkCOROlhwIfyzHarhr82IjW8H5DoEqNKgs0fBww6OiQmnL3lJe7O0vKYU1jVmbFLziKJeLaN9dyJr1JdXMBCSs2NMJlfcV3ddRWNXa0mDXiTshPyhyUbozDWwB0SOvz5xIGDW2OoXfig4DDKqGL/d1oo7XbnhJ8yC10FZUntDZ+aEuEvb+AYDbsBqTFVkBbN2UEGMoyslxNlzPasIyQpUAQBmQZvMpzjFEMM/Bdy4TsT+4RXvNsChc78TiI8A1OblXlKMHVnHAvGavTfAb35Fnyf0cMUjKnj7fs4lMRijhGhCISV7x5YsTyWzRAcmLQi7Fyss+j4Yl34Wdt9EtQtUhgpq8OuMT9nNiy3kq77XtgI6Hm7AUBjPq3h3KxKcqdSKNbbJkdwgNZQBFU0rMIAOuwAXDn3CB2eCRIT2zoG77ic2rd1U="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
