travis:
  secure:
    BINSTAR_TOKEN: Umu8C89Z07BKbEIqUTd8+hIA8fDOWBYAH937UHEtbX97Y4m6616Srb5Zqi4hxCBEPB2IB1pL12JKG4lgNR/Ciz5rjSOZ1bDkGS1RxwtIjl8nhCbxhF+nzYIZRBipSvPQd6FkT4IQoN8StxrJAl22kIt/ibfG6ACOkrqWv6ihjORmUxkx/6pGvE0DUYzTV6GA6A8RwO+Wu3wJ5ejO2uO24pe8+HRE8QtQZm4svOH9aWVKaqAN5oKBB79MemvkCOROlhwIfyzHarhr82IjW8H5DoEqNKgs0fBww6OiQmnL3lJe7O0vKYU1jVmbFLziKJeLaN9dyJr1JdXMBCSs2NMJlfcV3ddRWNXa0mDXiTshPyhyUbozDWwB0SOvz5xIGDW2OoXfig4DDKqGL/d1oo7XbnhJ8yC10FZUntDZ+aEuEvb+AYDbsBqTFVkBbN2UEGMoyslxNlzPasIyQpUAQBmQZvMpzjFEMM/Bdy4TsT+4RXvNsChc78TiI8A1OblXlKMHVnHAvGavTfAb35Fnyf0cMUjKnj7fs4lMRijhGhCISV7x5YsTyWzRAcmLQi7Fyss+j4Yl34Wdt9EtQtUhgpq8OuMT9nNiy3kq77XtgI6Hm7AUBjPq3h3KxKcqdSKNbbJkdwgNZQBFU0rMIAOuwAXDn3CB2eCRIT2zoG77ic2rd1U=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
