travis:
  secure:
    BINSTAR_TOKEN: LRTYVOk+sA3esnpCpRfiPDC8JCHVHzaOhOKO4Lyl0k+fanSAXxiYUc04a42bN/sixgqfAMERJTGPZZyrQDUepm67bcRUc3r6BS5/pC2xTlF9Va7DjxhVK+76nVe+BgO1frPVVyftCNcvauTz3ls0kpd6c/qYsrCGXe2wtVPsWxy5pC1jYLP6JBvOr9wFQPTkIr5HFr/E5RN5n5zeoNJP3FTnHrBjq61pH2Oe5xENfOaIqwctiKBGw+RMPuS2eapRQ9NR7cfPNzznlhZCaoxBd4ncx83/AzZ4wILfd8euY9MmzsQyxh6JKYEVhnMEA2vqmoxzhHUf2rW7boUXhN8Uu3yFl7LAlFWyXVc9eXOle1+DTwicCPROwYxp0g3MkCwUPZO0Gq6y11aWDxKy+0Mpg87/0uC8Id2FaMT9T0jrh05Loz32/Fsc8fgOUv4nlX6yzg7Emboo+TXYUMRN/EekTUoDysFDXX5EbJpjC1U5pb70PSFU2Oi+jqeBTwCo0N51e7FwM6DjBk9VQmWH78OstSZl4wkZPx7ioA0ch8nfN7KC/h70s8i4IZqmntwq46WIAGv7q7rL/Lz46pfZs2cj09AY5Itb2K1dNGbKTOiJpHByv21adNXaaniWrSgXlC1+N5pYXuc7q/KdXpYw/vriuG+gkpgmxyyg/jtDhMwDgkM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
